### ISSUE TITLE
asm instructions in sihaHLSdm

### ISSUE THREAD

**Issue by talhaHavadar** [Xilinx/dfx-mgr#4]
I see that in [sihaHLSdm.c](https://github.com/Xilinx/dfx-mgr/blob/master/src/sys/linux/graph/layer0/sihaHLS/sihaHLSdm.c) there  are specific instructions like below:

```
asm volatile("dmb ishld" ::: "memory");
```
Does these instructions required to make the application work? Why are we using these? I am asking because I wanted to build the dfx-mgr for all architectures but it seems like these are the only things that cause the build to fail. 

I can understand the main focus of dfx-mgr is arm64 but it is almost always handy to have debian packages built for multiple architectures. In case in the future, dfx-mgr could be utilized in some other cpu architecture then we would already have it built in the archive.

**Comment by arunkann** [comment]
This code is part of a prototype effort, and shouldn't be required for baseline, normal operation of dfxmgr.
We will remove it completely in our next release.

**Comment by arunkann** [comment]
this code was removed in master
